# Imports

In [1]:
import numpy as np

In [2]:
from numpy.random import random as rando
rando((5, 5))

array([[0.97804705, 0.60644556, 0.58759365, 0.24691574, 0.02162171],
       [0.71131521, 0.30414781, 0.78235492, 0.57476037, 0.10778452],
       [0.06586756, 0.61611237, 0.63782751, 0.01710635, 0.18934712],
       [0.07823646, 0.57031809, 0.00770644, 0.62487671, 0.3192615 ],
       [0.45867425, 0.48356245, 0.83232841, 0.9812974 , 0.17731175]])

In [3]:
import opt_imports as optim

In [4]:
from opt_imports.optional_imports import _optional_import
np = _optional_import('numpy')
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
nonexistent = _optional_import('nonexistent_package')
try:
    nonexistent.function()
except ValueError as e:
    print(e)

Install the `nonexistent_package` package to make use of this feature.


In [6]:
nonexistent = _optional_import('nonexistent_package')
try:
    _ = nonexistent.variable
except ValueError as e:
    print(e)

Install the `nonexistent_package` package to make use of this feature.


In [7]:
rando = _optional_import('numpy', 'random.random')

In [8]:
np.random.seed(1)
np.round(rando((5, 5)) * 20, 0)

array([[ 8., 14.,  0.,  6.,  3.],
       [ 2.,  4.,  7.,  8., 11.],
       [ 8., 14.,  4., 18.,  1.],
       [13.,  8., 11.,  3.,  4.],
       [16., 19.,  6., 14., 18.]])

In [9]:
xr = _optional_import('xarray')

In [10]:
optim.sub_package_2.get_xarray_version()

ValueError: Install the `xarray` package with version `>=0.17.0` to make use of this feature.

In [ ]:
from opt